#    phy
#    an airplug compatible program
#    author: Bertrand Ducourthial AT utc.fr, Anthony Buisset (v0.1)
#    license type: free of charge license for academic and research purpose
#    see license.txt
###############################################################################

set PHY_rad_puissance_emission 1
set PHY_rad_amplification_reception 1

set PHY_mnemopuissance "p"
set PHY_mnemoposition "g"
