#    rte
#    an airplug compatible program
#    author: Bertrand Ducourthial AT utc.fr, Anthony Buisset (v0.1)
#    license type: free of charge license for academic and research purpose
#    see license.txt
###############################################################################

# Mnemonique pour le header RTE, contenant le nom de l'application qui a emis
# le message transporte.
set RTE_rc_mnemoapp "apprte"
