#    hlg
#    an airplug compatible program
#    author: Yann DRONIOU et Marc-Antoine MARTIN UTC
#    license type: free of charge license for academic and research purpose
#    see license.txt
### MODULE HORLOGE ##########################################################

package require math

### VARIABLES DU MODULE #######################################################

set HLG_lam_h 0

###############################################################################

### ZONE DU MODULE ############################################################

labelframe .lam -pady 2 -padx 2 -text "Lamport Clock \[$APP, ident = $APG_ident\]" \
				-fg $APG_int_coltitle

# sous-zone variable snapshot avec descritif
label .lam.t -text "Lamport clock: "
label .lam.h -textvariable HLG_lam_h -width 4

# affichage des sous-zones de la zone snp
pack .lam.t .lam.h -side left -fill y -pady 2

###############################################################################

### PROCEDURES OF THE MODULE ##################################################

proc HLG_lam_get {} {
	return $::HLG_lam_h
}

#-- Procedure HLG_lam_incrandget ---------------------------------------------#
# Action : incremente the clock and return it                                 #
# Input  : nothing                                                            #
# Output : clock                                                              #
#-----------------------------------------------------------------------------#
proc HLG_lam_incrandget { } {
    incr ::HLG_lam_h
    return $::HLG_lam_h
}
 
#-- Procedure HLG_lam_update -------------------------------------------------#
# Action : update the clock, h <- max(h_rcv, h) + 1                           #
# Input  : received clock                                                     #
# Output : nothing                                                            #
#-----------------------------------------------------------------------------#
proc HLG_lam_update { h_rcv } {
    set ::HLG_lam_h [::math::max $h_rcv $::HLG_lam_h ]
    incr ::HLG_lam_h
}
###############################################################################
